### ISSUE TITLE
Crash in cli & UI

### ISSUE THREAD

**Issue by sniper-developer** [tvdburgt/subtle#13]
Crash when starting search for some files.
I have reproduce on this torrent
https://kat.cr/robot-chicken-s08e17-food-1080p-hdtv-x264-mkv-zeus-t12527157.html

Unhandled Exception: System.AggregateException: One or more errors occurred. ---> CookComputing.XmlRpc.XmlRpcServerException: Backend fetch failed
   at CookComputing.XmlRpc.XmlRpcClientProtocol.ReadResponse(XmlRpcRequest req, WebResponse webResp, Stream respStm)
   at CookComputing.XmlRpc.XmlRpcClientProtocol.EndInvoke(IAsyncResult asr, Type returnType)
   at XmlRpcProxy06183dd3-e70c-4990-9e84-80b52e6ee685.EndLogIn(IAsyncResult )
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Subtle.Model.TaskExtensions.<WithTimeout>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Subtle.Model.OSDbClient.<InitSessionAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Subtle.Cli.Program.<MainAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
##    at Subtle.Cli.Program.Main(String[] args)

P.S. subtitle itself seemed to be bad indeed, link led to error page. Some time later, it was ok, and UI version was able to download, but a bit later - error again.

**Comment by tvdburgt** [comment]
This is probably a server error. Errors like this need to be handled more gracefully (instead of throwing an exception and crashing the application).

**Comment by tvdburgt** [comment]
This is resolved in v0.4.2.
