### ISSUE TITLE
Error While Using Subtle-cli

### ISSUE THREAD

**Issue by sebinpj** [tvdburgt/subtle#20]
when using subtle-cli to download subtitles of an entire directory the following error happens

`[Hash]       scrubs.2x02.my_nightingale.dvdrip_xvid-fov.avi`
 `[Hash]       scrubs.2x01.my_overkill.dvdrip_xvid-fov.avi`
`
Unhandled Exception: System.Net.WebException: Request timed out
   at Subtle.Model.TaskExtensions.<WithTimeout>d__01.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Subtle.Model.OSDbClient.<SearchSubtitlesAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Subtle.Cli.Program.<SearchSubtitleAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Subtle.Cli.Program.<MainAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Subtle.Cli.Program.Main(String[] args)`

this error seem to be so frequent while using subtle-cli (On subtle 0.41)

My Opensubtitles statistics  

![image](https://cloud.githubusercontent.com/assets/8169523/22579746/89824c0a-e9f8-11e6-8120-40102303ab27.png)

**Comment by tvdburgt** [comment]
This is resolved in v0.4.2.
