### ISSUE TITLE
Unhandled Exception Error

### ISSUE THREAD

**Issue by DonCaliOni** [tvdburgt/subtle#33]
Hi, I have suddenly started to getting an Unhandled exception error when opening Suble. I have attached a screenshot and a Notepad dump of the detailed error text. I haven't really changed anything so not sure what is causing it. Hitting continue doesn't help.

<img width="329" alt="Suble Error" src="https://user-images.githubusercontent.com/80406264/150644376-0a58f546-fd3b-4971-8e96-8c443076dbea.PNG">

[Suble Error Log.txt](https://github.com/tvdburgt/subtle/files/7918619/Suble.Error.Log.txt)

**Comment by fleinbach** [comment]
I am receiving the same error message.

ee the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
CookComputing.XmlRpc.XmlRpcTypeMismatchException: response contains boolean value where array expected [response : struct mapped to type SubtitleFileCollection : member Files mapped to type SubtitleFile[]]
   at CookComputing.XmlRpc.XmlRpcDeserializer.CheckExpectedType(Type expectedType, Type actualType, MappingStack mappingStack)
   at CookComputing.XmlRpc.XmlRpcDeserializer.MapBoolean(String value, Type valType, MappingStack mappingStack, MappingAction mappingAction, Type& mappedType)
   at CookComputing.XmlRpc.XmlRpcDeserializer.MapValueNode(IEnumerator`1 iter, Type valType, MappingStack mappingStack, MappingAction mappingAction)
   at CookComputing.XmlRpc.XmlRpcDeserializer.<>c__DisplayClass22.<MapStruct>b__1f()
   at CookComputing.XmlRpc.XmlRpcDeserializer.OnStack[T](String p, MappingStack mappingStack, Func`1 func)
   at CookComputing.XmlRpc.XmlRpcDeserializer.MapStruct(IEnumerator`1 iter, Type valueType, MappingStack mappingStack, MappingAction mappingAction, Type& mappedType)
   at CookComputing.XmlRpc.XmlRpcDeserializer.MapValueNode(IEnumerator`1 iter, Type valType, MappingStack mappingStack, MappingAction mappingAction)
   at CookComputing.XmlRpc.XmlRpcResponseDeserializer.DeserializeResponse(XmlReader rdr, Type returnType)
   at CookComputing.XmlRpc.XmlRpcResponseDeserializer.DeserializeResponse(Stream stm, Type svcType)
   at CookComputing.XmlRpc.XmlRpcClientProtocol.ReadResponse(XmlRpcRequest req, WebResponse webResp, Stream respStm)
   at CookComputing.XmlRpc.XmlRpcClientProtocol.EndInvoke(IAsyncResult asr, Type returnType)
   at XmlRpcProxya57c513c-0415-4d3d-8356-0da28cb767a6.EndDownloadSubtitles(IAsyncResult )
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Subtle.Model.TaskExtensions.<WithTimeout>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Subtle.Model.OSDbClient.<ExecuteOSDbTask>d__18`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Subtle.Gui.MainForm.<DownloadSubtitle>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Subtle.Gui.MainForm.<DownloadButtonClick>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Comment by billmcct** [comment]
Well, I guess "Subtle" is dead. Nothing since 2017.
Getting the same "Unhandled exception".
![2024-01-05 12_44_52-Subtle](https://github.com/tvdburgt/subtle/assets/35135114/ba8a00cc-b5d0-43c6-a329-e9a05c5e6983)

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
CookComputing.XmlRpc.XmlRpcTypeMismatchException: response contains integer value where string expected [response : struct mapped to type SubtitleFileCollection : member Files mapped to type SubtitleFile[] : array mapped to type SubtitleFile[] : element 0 : struct mapped to type SubtitleFile : member Id mapped to type String]
   at CookComputing.XmlRpc.XmlRpcDeserializer.CheckExpectedType(Type expectedType, Type actualType, MappingStack mappingStack)
   at CookComputing.XmlRpc.XmlRpcDeserializer.MapInt(String value, Type valType, MappingStack mappingStack, MappingAction mappingAction, Type& mappedType)
   at CookComputing.XmlRpc.XmlRpcDeserializer.MapValueNode(IEnumerator`1 iter, Type valType, MappingStack mappingStack, MappingAction mappingAction)
   at CookComputing.XmlRpc.XmlRpcDeserializer.<>c__DisplayClass22.<MapStruct>b__1f()
   at CookComputing.XmlRpc.XmlRpcDeserializer.OnStack[T](String p, MappingStack mappingStack, Func`1 func)
   at CookComputing.XmlRpc.XmlRpcDeserializer.MapStruct(IEnumerator`1 iter, Type valueType, MappingStack mappingStack, MappingAction mappingAction, Type& mappedType)
   at CookComputing.XmlRpc.XmlRpcDeserializer.MapValueNode(IEnumerator`1 iter, Type valType, MappingStack mappingStack, MappingAction mappingAction)
   at CookComputing.XmlRpc.XmlRpcDeserializer.MapArray(IEnumerator`1 iter, Type valType, MappingStack mappingStack, MappingAction mappingAction, Type& mappedType)
   at CookComputing.XmlRpc.XmlRpcDeserializer.MapValueNode(IEnumerator`1 iter, Type valType, MappingStack mappingStack, MappingAction mappingAction)
   at CookComputing.XmlRpc.XmlRpcDeserializer.<>c__DisplayClass22.<MapStruct>b__1f()
   at CookComputing.XmlRpc.XmlRpcDeserializer.OnStack[T](String p, MappingStack mappingStack, Func`1 func)
   at CookComputing.XmlRpc.XmlRpcDeserializer.MapStruct(IEnumerator`1 iter, Type valueType, MappingStack mappingStack, MappingAction mappingAction, Type& mappedType)
   at CookComputing.XmlRpc.XmlRpcDeserializer.MapValueNode(IEnumerator`1 iter, Type valType, MappingStack mappingStack, MappingAction mappingAction)
   at CookComputing.XmlRpc.XmlRpcResponseDeserializer.DeserializeResponse(XmlReader rdr, Type returnType)
   at CookComputing.XmlRpc.XmlRpcResponseDeserializer.DeserializeResponse(Stream stm, Type svcType)
   at CookComputing.XmlRpc.XmlRpcClientProtocol.ReadResponse(XmlRpcRequest req, WebResponse webResp, Stream respStm)
   at CookComputing.XmlRpc.XmlRpcClientProtocol.EndInvoke(IAsyncResult asr, Type returnType)
   at XmlRpcProxya8dfc69c-ca7b-4a38-b0e3-1d558da1ef44.EndDownloadSubtitles(IAsyncResult )
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Subtle.Model.TaskExtensions.<WithTimeout>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Subtle.Model.OSDbClient.<ExecuteOSDbTask>d__18`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Subtle.Gui.MainForm.<DownloadSubtitle>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Subtle.Gui.MainForm.<DownloadButtonClick>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4645.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
subtle
    Assembly Version: 1.0.0.0
    Win32 Version: 0.4.2
    CodeBase: file:///C:/Program%20Files%20(x86)/Subtle/subtle.exe
----------------------------------------
Subtle.Model
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Subtle/Subtle.Model.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4654.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4682.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4395.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Octokit
    Assembly Version: 0.17.0.0
    Win32 Version: 0.17.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Subtle/Octokit.DLL
----------------------------------------
AutoMapper
    Assembly Version: 4.0.4.0
    Win32 Version: 4.0.4.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Subtle/AutoMapper.DLL
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4682.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
CookComputing.XmlRpcV2
    Assembly Version: 3.0.0.0
    Win32 Version: 3.0.0.266
    CodeBase: file:///C:/Program%20Files%20(x86)/Subtle/CookComputing.XmlRpcV2.DLL
----------------------------------------
XmlRpcProxya8dfc69c-ca7b-4a38-b0e3-1d558da1ef44
    Assembly Version: 0.0.0.0
    Win32 Version: 3.0.0.266
    CodeBase: file:///C:/Program%20Files%20(x86)/Subtle/CookComputing.XmlRpcV2.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Security
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4261.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.4645.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
